### ISSUE TITLE
Option to specify releases?

### ISSUE THREAD

**Issue by LaFong** [plugwash/raspbian-tools#1]
Feature request: It seems there is no option to specify which releases to mirror. So, it downloads bullseye, which we do not need currently, and has no option for older releases.

**Comment by plugwash** [comment]
Yeah, I want to add this feature, I need to add some extra stuff on the generation side though, so it can correctly work-out what files to download in the case of a limited set of releases.

**Comment by plugwash** [comment]
Ok, I have added the server side stuff to generate the "extrasources" files. Now for the client-side stuff.

**Comment by plugwash** [comment]
Ok, you can now specify which releases you want with the "--distswhitelist" option, for example "--distswhitelist stretch,buster"

**Comment by diederikdehaas** [comment]
When I tried the following command:
`../raspbmirror.py --tmpdir ../tmp/ --distswhitelist "stretch,buster,bullseye"`
I got this as result:
```
stage 1, scan existing
stage 2, main download
missing extra sources file for multiarch/dists/bullseye
missing extra sources file for multiarch/dists/buster
```
And then it stopped.

**Comment by plugwash** [comment]
This is my fault, it seems that the multiarch repo doesn't have the extra data files that this feature needs, i'll try to look at that soon.

In the meantime you should be able to skip mirroring the multiarch repo with

../raspbmirror.py --tmpdir ../tmp/ --distswhitelist "stretch,buster,bullseye" --tlwhitelist raspbian

**Comment by diederikdehaas** [comment]
That indeed seems to work, thanks.

I (still) went with the Partial Mirroring feature of `apt-cacher-ng`, because that allowed me to only get the binary packages for an archive area of a release, iow I could further (severely) limit what would be downloaded.
I'm using the following setting in `acng.conf` to achieve that.
`PrecacheFor: mirrordirector.raspbian.org/raspbian/dists/buster/main/binary-armhf/Packages*`

Your tool seems better suited for the job at hand, but it would DL a lot of what I'm not interested it (now). If I could further limit what to DL with your tool and can import (or otherwise reuse) the data into `apt-cacher-ng` (and vice-versa), that would be great. No idea whether it's worth the/your time investment.

**Comment by plugwash** [comment]
Without knowing what exactly your goals are it's hard to advise, I wrote raspbmirror primerally to produce complete copyleft-compilant mirrors of the raspbian archive. If you aren't mirroring source anyway (something you should only do for private mirrors) then it's probablly not the tool for you.

**Comment by diederikdehaas** [comment]
I need a partial offline mirror. I'm working on 'my' net-installer again, but my fast internet connection will soon end; only mobile for a while and then a much slower normal connection. In order to build it, a bunch of packages will be DL-ed and when testing it, it installs a bunch more. But it now/soon all those packages will need to be present on my LAN.

I can totally understand if that's not an intended use case, but for buster main alone, it's ~70GB.

**Comment by malaire** [comment]
Why is this closed even though `--distswhitelist bullseye` still doesn't work?

**Comment by LaFong** [comment]
It works for me, though I am still in the bullseye testing phase. I use this:
.,/raspbmirror.py --tlwhitelist raspbian --distwhitelist stretch,buster,bullseye --cleanup

**Comment by malaire** [comment]
I didn't test with `--tlwhitelist raspbian` because I don't want to leave out anything important, and it doesn't seem to be documented at all of what those other files are which are not included with `--tlwhitelist raspbian`.
